version: '3.7'

services:

  base-dashboard:
    container_name: base-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/home/node/app/src'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true